### PR TITLE
Go generation improvements for boxes

### PR DESCRIPTION
**Pull request by jasonpaulos**
This PR makes the following changes to Go code generation:
* Required query parameters are now treated differently. Instead of using the builder pattern to set these properties, they must be passed in during the creation of the query object. Additionally, the builder function used to set these properties is now private, so they cannot be modified after creation.
  * Before the new box endpoints, we did not have any required query parameters, so this doesn't change our existing code in any way.
  * Here's an example:
```go
//  --- Before this PR ---

// definition
func (c *Client) GetApplicationBoxByName(applicationId uint64) *GetApplicationBoxByName {
	return &GetApplicationBoxByName{c: c, applicationId: applicationId}
)

// usage
client.GetApplicationBoxByName(applicationId).Name(name).Do(context.Background())

// --- After this PR ---

// definition
func (c *Client) GetApplicationBoxByName(applicationId uint64, name []byte) *GetApplicationBoxByName {
	return (&GetApplicationBoxByName{c: c, applicationId: applicationId}).name(name)
)

// usage
client.GetApplicationBoxByName(applicationId, name).Do(context.Background())
```
  * Algod and indexer both have a `/v2/applications/{appId}/box` endpoint which is nonstandard. This endpoint has a required query parameter `name` that follows a special convention. This `name` parameter is typed as a string, but it's really meant to express arbitrary byte arrays. I've added a special case for this specific parameter such that SDK users can provide a byte slice which is automatically converted to a properly formatted string.
    * Here's an example:
```go
//  --- Before this PR ---

// definition
func (s *GetApplicationBoxByName) name(name string) *GetApplicationBoxByName {
	s.p.Name = Name

	return s
}

// usage
var boxName []byte // somehow populated
boxNameStr := encoding.EncodeBytesForBoxQuery(boxName)
client.GetApplicationBoxByName(applicationId, boxNameStr).Do(context.Background())

// --- After this PR ---

// definition
func (s *GetApplicationBoxByName) name(name []byte) *GetApplicationBoxByName {
	s.p.Name = "b64:" + base64.StdEncoding.EncodeToString(name)

	return s
}

// usage
var boxName []byte // somehow populated
client.GetApplicationBoxByName(applicationId, boxName).Do(context.Background())
```

While the changes in these PR are not technically necessary, they do improve the ergonomics for end users.

I have not attempted to bring similar changes to the Java SDK because its client generation does not appear to use templates, so changing it seems more involved and likely isn't worth it at this time.

### CODE REVIEW

**Comment by jasonpaulos** [comment]
This branch was used to generate the code in https://github.com/algorand/go-algorand-sdk/pull/417

**Review by tzaffi — COMMENTED** [review]
Seems good to me, but blocked by understanding the `BlockHash` generation reason (which I suspect has nothing to do with any of the code changes here).

**Comment by michaeldiamant** [comment]
I'm on the fence - If someone leaves approval, I won't stand in the way.

* The generated changes are definitely an ergonomics improvement.  
* I'm concerned about the maintenance costs associated with more complicated _generator_ templating.  Feel welcomed to disregard my concern.

**Review by michaeldiamant — APPROVED** [review]
I primarily vetted the PR based on its generated changes in https://github.com/algorand/go-algorand-sdk/pull/417.

**Pull request merged**
